# Generated by Django 4.2.3 on 2023-07-21 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datatable",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=200)),
                ("customer", models.CharField(max_length=200)),
                ("dc_no", models.IntegerField()),
                ("Part_no", models.CharField(max_length=200)),
                ("returnable", models.CharField(max_length=200)),
                ("remarks", models.CharField(max_length=200)),
                ("project", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time_stamp", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
