# Generated by Django 4.2.3 on 2023-07-21 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATRIX_MK1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatable",
            name="time_stamp",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
