# Generated by Django 4.2.3 on 2023-07-25 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATRIX_MK1", "0005_alter_datatable_time_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatable",
            name="time_stamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 25, 14, 35, 32, 92765)
            ),
        ),
    ]
