# Generated by Django 3.2.20 on 2023-07-27 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATRIX_MK1', '0006_alter_datatable_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 12, 26, 34, 976592)),
        ),
    ]
